### ISSUE TITLE
Fix deprecation warning

### ISSUE THREAD

**Issue by XhmikosR** [jsdelivr/bootstrapcdn#429]
```
Wed, 05 Nov 2014 07:34:13 GMT morgan deprecated undefined format: specify a format at app.js:36:13
Wed, 05 Nov 2014 07:34:13 GMT morgan deprecated undefined format: specify a format at app.js:36:13
Wed, 05 Nov 2014 07:34:13 GMT morgan deprecated default format: use combined format at app.js:36:13
Wed, 05 Nov 2014 07:34:13 GMT morgan deprecated default format: use combined format at app.js:36:13
```

**Comment by lpxxn** [comment]
var morgan = require('morgan');
app.use(morgan('combined'));
